name: basic build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  basic-linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64
          - x86
          - aarch64
          - armv7
    steps:
      - uses: actions/checkout@v4
      - name: Basic Build on Linux
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release
          sccache: 'true'

  basic-windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x64
          - x86
    steps:
      - uses: actions/checkout@v4
      - name: Basic Build on Windows
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release
          sccache: 'true'

  basic-macos-build:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v4
      - name: Basic Build on macOS
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release
          sccache: 'true'
